# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='im_client',
  serialized_pb=_b('\n\x0emessages.proto\x12\tim_client\"+\n\x0bInitMessage\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06secret\x18\x02 \x02(\t\"\xa2\x01\n\x10InitErrorMessage\x12\x38\n\x05\x65rror\x18\x01 \x02(\x0e\x32).im_client.InitErrorMessage.InitErrorCode\"T\n\rInitErrorCode\x12\x13\n\x0fIncorrectSecret\x10\x00\x12\x15\n\x11\x41lreadyRegistered\x10\x01\x12\x17\n\x13\x45xpectedInitMessage\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_INITERRORMESSAGE_INITERRORCODE = _descriptor.EnumDescriptor(
  name='InitErrorCode',
  full_name='im_client.InitErrorMessage.InitErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IncorrectSecret', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AlreadyRegistered', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExpectedInitMessage', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=153,
  serialized_end=237,
)
_sym_db.RegisterEnumDescriptor(_INITERRORMESSAGE_INITERRORCODE)


_INITMESSAGE = _descriptor.Descriptor(
  name='InitMessage',
  full_name='im_client.InitMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='im_client.InitMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secret', full_name='im_client.InitMessage.secret', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=72,
)


_INITERRORMESSAGE = _descriptor.Descriptor(
  name='InitErrorMessage',
  full_name='im_client.InitErrorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='im_client.InitErrorMessage.error', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INITERRORMESSAGE_INITERRORCODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=237,
)

_INITERRORMESSAGE.fields_by_name['error'].enum_type = _INITERRORMESSAGE_INITERRORCODE
_INITERRORMESSAGE_INITERRORCODE.containing_type = _INITERRORMESSAGE
DESCRIPTOR.message_types_by_name['InitMessage'] = _INITMESSAGE
DESCRIPTOR.message_types_by_name['InitErrorMessage'] = _INITERRORMESSAGE

InitMessage = _reflection.GeneratedProtocolMessageType('InitMessage', (_message.Message,), dict(
  DESCRIPTOR = _INITMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:im_client.InitMessage)
  ))
_sym_db.RegisterMessage(InitMessage)

InitErrorMessage = _reflection.GeneratedProtocolMessageType('InitErrorMessage', (_message.Message,), dict(
  DESCRIPTOR = _INITERRORMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:im_client.InitErrorMessage)
  ))
_sym_db.RegisterMessage(InitErrorMessage)


# @@protoc_insertion_point(module_scope)
